<Project>
	<Target Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
		<Exec Command="git describe --long --always --dirty --exclude=* --abbrev=8" StandardOutputImportance="low" StandardErrorImportance="low" ConsoleToMSBuild="True" IgnoreExitCode="False" ContinueOnError="True">
			<Output PropertyName="SourceRevisionIdOutput" TaskParameter="ConsoleOutput"/>
			<Output PropertyName="SourceRevisionIdErrorCode" TaskParameter="ExitCode"/>
		</Exec>
		<Exec Command="git rev-parse HEAD" StandardOutputImportance="low" StandardErrorImportance="low" ConsoleToMSBuild="True" IgnoreExitCode="False" ContinueOnError="True">
			<Output PropertyName="SourceRevisionIdFullOutput" TaskParameter="ConsoleOutput"/>
			<Output PropertyName="SourceRevisionIdFullErrorCode" TaskParameter="ExitCode"/>
		</Exec>
		<Exec Command="git rev-parse --abbrev-ref HEAD" StandardOutputImportance="low" StandardErrorImportance="low" ConsoleToMSBuild="True" IgnoreExitCode="False" ContinueOnError="True">
			<Output PropertyName="SourceBranchOutput" TaskParameter="ConsoleOutput"/>
			<Output PropertyName="SourceBranchErrorCode" TaskParameter="ExitCode"/>
		</Exec>
		<PropertyGroup>
			<GitRepo>false</GitRepo>
			<SourceRevisionId></SourceRevisionId>
			<SourceRevisionIdFull></SourceRevisionIdFull>
			<SourceBranch></SourceBranch>
		</PropertyGroup>
		<PropertyGroup Condition="'$(SourceRevisionIdErrorCode)' == '0'">
			<GitRepo>true</GitRepo>
			<SourceRevisionId>$(SourceRevisionIdOutput)</SourceRevisionId>
		</PropertyGroup>
		<PropertyGroup Condition="'$(SourceRevisionIdFullErrorCode)' == '0'">
			<SourceRevisionIdFull>$(SourceRevisionIdFullOutput)</SourceRevisionIdFull>
		</PropertyGroup>
		<PropertyGroup Condition="'$(SourceBranchErrorCode)' == '0'">
			<SourceBranch>$(SourceBranchOutput)</SourceBranch>
		</PropertyGroup>
		<PropertyGroup>
			<GitData>
				<![CDATA[
using System%3B
internal partial class ThisAssembly
{
    internal class Git {
        internal const bool IsGitRepo = $(GitRepo)%3B
        internal const string SourceRevisionId = "$(SourceRevisionId)"%3B
        internal const string SourceRevisionIdFull = "$(SourceRevisionIdFull)"%3B
        internal const string SourceBranch = "$(SourceBranch)"%3B
    }
}
      ]]>
			</GitData>
			<InformationalData>
				<![CDATA[
using System%3B
internal partial class ThisAssembly
{
    internal class InformationalData {
        internal const string Version = "$(Version)"%3B
        internal const string Codename = "$(Codename)"%3B
        internal const string LabId = "$(Lab)"%3B
        internal const string BuildDateTime = "$([System.DateTime]::Now.ToString("yyyyMMdd_HHmmss"))"%3B
        internal const string BuildStage = "$(Configuration)"%3B
    }
}
      ]]>
			</InformationalData>
		</PropertyGroup>
		<PropertyGroup>
			<GitGeneratedFilePath>$(IntermediateOutputPath)GitAssemblyInformation.g.cs</GitGeneratedFilePath>
			<InformationalGeneratedFilePath>$(IntermediateOutputPath)InformationalAssemblyInformation.g.cs</InformationalGeneratedFilePath>
		</PropertyGroup>
		<ItemGroup>
			<Compile Include="$(GitGeneratedFilePath)" />
			<FileWrites Include="$(GitGeneratedFilePath)" />
			<Compile Include="$(InformationalGeneratedFilePath)" />
			<FileWrites Include="$(InformationalGeneratedFilePath)" />
		</ItemGroup>
		<WriteLinesToFile Lines="$(GitData)" File="$(GitGeneratedFilePath)" WriteOnlyWhenDifferent="true" Overwrite="true" />
		<WriteLinesToFile Lines="$(InformationalData)" File="$(InformationalGeneratedFilePath)" WriteOnlyWhenDifferent="true" Overwrite="true" />
	</Target>
</Project>
