<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputType>WinExe</OutputType>
		<AssemblyName>XCP-ng Center</AssemblyName>
		<ApplicationIcon>AppIcon.ico</ApplicationIcon>
		<Title>XCP-ng Center</Title>
		<Description>XCP-ng Center</Description>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.ReportViewer.Runtime.WinForms" Version="12.0.2402.15" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XenModel\XenModel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Design" />
		<Reference Include="System.Management" />
		<Reference Include="System.Security" />
		<Reference Include="System.Windows.Forms.DataVisualization" />
		<Reference Include="System.Web" />
		<Reference Include="System.Web.Extensions" />
		<Reference Include="AxMSTSCLib">
			<HintPath>RDP\AxMSTSCLib.dll</HintPath>
		</Reference>
		<Reference Include="MSTSCLib">
			<HintPath>RDP\MSTSCLib.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="VNC\KeyMap.resx">
			<LogicalName>DotNetVnc.KeyMap.resources</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Wizards\NewSRWizard_Pages\ChooseSrProvisioningPage.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ChooseSrProvisioningPage.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Wizards\NewSRWizard_Pages\ChooseSrProvisioningPage.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>ChooseSrProvisioningPage.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="&quot;$(TargetFrameworkSDKToolsDirectory)aximp.exe&quot; $(WinDir)\System32\mstscax.dll" WorkingDirectory="$(ProjectDir)RDP" />
	</Target>
</Project>