<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputType>WinExe</OutputType>
		<AssemblyName>XCP-ng Center</AssemblyName>
		<ApplicationIcon>AppIcon.ico</ApplicationIcon>
		<Title>XCP-ng Center</Title>
		<Description>XCP-ng Center</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\XenModel\XenModel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MSTSCLib" Version="1.0.0" />
		<PackageReference Include="Microsoft.ReportViewer" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="System.Design" />
		<Reference Include="System.Management" />
		<Reference Include="System.Security" />
		<Reference Include="System.Windows.Forms.DataVisualization" />
		<Reference Include="System.Web" />
		<Reference Include="System.Web.Extensions" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="VNC\KeyMap.resx">
			<LogicalName>DotNetVnc.KeyMap.resources</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Wizards\NewSRWizard_Pages\ChooseSrProvisioningPage.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>ChooseSrProvisioningPage.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Wizards\NewSRWizard_Pages\ChooseSrProvisioningPage.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>ChooseSrProvisioningPage.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
</Project>