<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<Title>XenModel</Title>
		<Description>XCP-ng Center library</Description>
		<RootNamespace>XenAdmin</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CookComputing.XmlRPCv2" Version="2.5.0" />
		<PackageReference Include="DiscUtils.Vhd" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Vhdx" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Vmdk" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Wim" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
		<PackageReference Include="lzfse-net" Version="1.0.15" />
		<PackageReference Include="lzo.net" Version="0.0.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CommandLib\CommandLib.csproj" />
		<ProjectReference Include="..\XenOvfApi\XenOvfApi.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.Web" />
		<Reference Include="System.Web.Extensions" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="FriendlyNames.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>FriendlyNames.resx</DependentUpon>
	  </Compile>
	  <Compile Update="InvisibleMessages.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>InvisibleMessages.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Messages.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Messages.resx</DependentUpon>
	  </Compile>
	  <Compile Update="UnitStrings.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>UnitStrings.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="FriendlyNames.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>FriendlyNames.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="InvisibleMessages.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>InvisibleMessages.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Messages.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Messages.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="UnitStrings.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>UnitStrings.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
</Project>